
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlRzn0evs-E1OwYFx3sOxRMo69j_mm1Ow',
    appId: '1:635902201905:web:f10069c73754d69b618510',
    messagingSenderId: '635902201905',
    projectId: 'sellco-project-tracker',
    authDomain: 'sellco-project-tracker.firebaseapp.com',
    storageBucket: 'sellco-project-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOKDC9UHsQxPFrSaS-Zhgszarr3fMZvEE',
    appId: '1:635902201905:android:0de4c09dc0c79b58618510',
    messagingSenderId: '635902201905',
    projectId: 'sellco-project-tracker',
    storageBucket: 'sellco-project-tracker.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKXeKDoa_J6taF7SIq_vp3IkM2nqS7ouE',
    appId: '1:635902201905:ios:09000bbfb377a74e618510',
    messagingSenderId: '635902201905',
    projectId: 'sellco-project-tracker',
    storageBucket: 'sellco-project-tracker.firebasestorage.app',
    iosBundleId: 'com.example.sellcoProjectTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlRzn0evs-E1OwYFx3sOxRMo69j_mm1Ow',
    appId: '1:635902201905:web:133e93285a6430ac618510',
    messagingSenderId: '635902201905',
    projectId: 'sellco-project-tracker',
    authDomain: 'sellco-project-tracker.firebaseapp.com',
    storageBucket: 'sellco-project-tracker.firebasestorage.app',
  );

}